# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airbrake < Formula
  desc "Airbrake CLI"
  homepage "https://airbrake.io"
  version "1.2.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/airbrake/airbrake-cli/releases/download/v1.2.8/airbrake_1.2.8_mac-os_x86_64.tar.gz"
      sha256 "123daee4a57b991a1e97fee6f44d749dd0ba1152351cc61b219f12cabd1b7f95"

      def install
        bin.install "airbrake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/airbrake/airbrake-cli/releases/download/v1.2.8/airbrake_1.2.8_mac-os_arm64.tar.gz"
      sha256 "9cb1cf4e6645e1330c9f0e4e85aca789336cf68322b04b3a31a603f22a7a8836"

      def install
        bin.install "airbrake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/airbrake/airbrake-cli/releases/download/v1.2.8/airbrake_1.2.8_linux_x86_64.tar.gz"
      sha256 "d0ff895ac8211fe94d9424fd8360e66986b93c0657a8617f239fa9b65218cc24"

      def install
        bin.install "airbrake"
      end
    end
  end
end
